# Generated by Django 5.0.3 on 2024-03-19 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_usuario_apellido_materno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id_tipo_usuario',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='usuarios.tipousuario'),
        ),
    ]
